/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music.player;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author Abhishek
 */
public class PlayerScreen extends javax.swing.JFrame 
{
       
        public String Playlist[]=new String[20];
        int f=-1,r=-1;
        public String name[]=new String[20];
        static PlayerScreen PlayerScreen=new PlayerScreen();
        FileFilter filter = new FileNameExtensionFilter("MP3 File", "mp3");
        public Boolean Playing=false;
	public javazoom.jl.player.Player player;
	public Thread t= Thread.currentThread();
	public FileInputStream fis = null;
	public long pauseLocation=0;
	public long songtotalLength=0;
        public int count=0;

        

    /**
     * Creates new form PlayerScreen
     */
    
       public PlayerScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\abhis\\Music\\Taylor Swift"));
        fileChooser.setDialogTitle("Select a .mp3 File");
        fileChooser.setFileFilter(filter);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 2, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 247, 93));
        jLabel2.setText("Music Player");

        jButton1.setBackground(new java.awt.Color(113, 216, 219));
        jButton1.setForeground(new java.awt.Color(41, 162, 60));
        jButton1.setText("Play");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(113, 216, 219));
        jButton3.setForeground(new java.awt.Color(255, 21, 60));
        jButton3.setText("Restart");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Now Playing: ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nothing Playing right now... Hit the Play Button");

        jPanel1.setBackground(new java.awt.Color(49, 79, 79));

        jButton2.setBackground(new java.awt.Color(113, 216, 219));
        jButton2.setText("Add in Playlist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(113, 216, 219));
        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(113, 216, 219));
        jButton5.setText("Previous");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(15, 105, 69));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(223, 255, 55));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton6.setBackground(new java.awt.Color(113, 216, 219));
        jButton6.setText("Add to Play Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        try {
            if(!Playing)
            {
                play();
            }
            else 
            pause();

            if(player.isComplete())
            {
                stop();
            }
        } catch (JavaLayerException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (InterruptedException ex) {
                Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        try {
            stop(); 
            play();        // TODO add your handling code here:
        } catch (InterruptedException | JavaLayerException | IOException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        Playlist[++r]=file.getPath();
        if(f==-1)
                f=0;

        name[r]=file.getName();
       print();
    } else {
        System.out.println("File access cancelled by user.");
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

 
    void print()
    {
        textArea.setText(null);
        for(int i=0;i<=r;i++)
        {
            if(f!=i)
                textArea.append(i+1+"]  "+ name[i]+"\n");
            else
                textArea.append(i+1+"]  "+ name[i]+"\t(Playing Right Now)\n");
        }
    }
    
    void shift(int s)
    {
        for(int i=r;i>=s;i--)
        {
           name[i+1]=name[i];
           Playlist[i+1]=Playlist[i];
        }
        r++;
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(Playing)
            try {
                stop();
        } catch (InterruptedException | JavaLayerException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                playnext();
            } catch (JavaLayerException | IOException | InterruptedException ex) {
                Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            print();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(Playing)
            try {
                stop();
        } catch (InterruptedException | JavaLayerException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                if(f==0)
                {
                    f=-1;
                }
                else
                    f=f-2;
                playnext();
            } catch (JavaLayerException | IOException | InterruptedException ex) {
                Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            print();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_SPACE)
         {
        try {
            if(!Playing)
            {
                play();
            }
            else 
            pause();
            //System.out.println("here");
            if(player.isComplete())
            {
                stop();
            }
        } catch (JavaLayerException | IOException | InterruptedException ex) {
            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();

        if(f==-1)
                f=0;

        shift(f+1);
        name[f+1]=file.getName();
        Playlist[f+1]=file.getPath();
        
       print();
    } else {
        System.out.println("File access cancelled by user.");
    }            // TO
    }//GEN-LAST:event_jButton6ActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayerScreen.setTitle("Music Player");
                PlayerScreen.setVisible(true);

            }
        });
    }
    
     void pause() throws InterruptedException, JavaLayerException, IOException
	{
		if(Playing)
                {
                    pauseLocation=fis.available();
                    System.out.println("The Pause Location: "+pauseLocation);
                    player.close();	
                    Playing=false;
                    jButton1.setText("Play");
                }
	}
    
    void play() throws JavaLayerException, IOException, InterruptedException
	{
		
            
            if(!Playing)
                {
                    //filename="07.  Breathe (feat. Colbie Caillat) [feat. Colbie Caillat] - Taylor Swift (320kbps).mp3";
                    fis = new FileInputStream(Playlist[f]);
                    player = new Player(fis);
                    jLabel4.setText(name[f]);
                    jButton1.setText("Pause");
                    
                    songtotalLength=fis.available();
                    
                    if(count==0)
                    {
                        pauseLocation=songtotalLength;
                        //pauseLocation=569186;
                    }
                    
                    try {
			fis.skip(songtotalLength-pauseLocation-15000);
		} catch (IOException e1) {
			
			
		}
                    
          
                new Thread()
                {
                    public void run()
                    {
                        try {
                            Playing=true;
                            count++;
                            player.play();
                           
                            
                                    } catch (JavaLayerException ex) {
                            
                        }
                        if(player.isComplete())
                        try {
                            checkComplete();
                                    
                                    } catch (InterruptedException | JavaLayerException | IOException ex) {
                            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }}
                }.start();
                
              
                }
		
	}
    
    
    
    
    void playnext() throws JavaLayerException, IOException, InterruptedException
	{
		
            if(!Playing)
                {
                    //filename="07.  Breathe (feat. Colbie Caillat) [feat. Colbie Caillat] - Taylor Swift (320kbps).mp3";
                    if(f==r)
                        f=-1;
                    fis = new FileInputStream(Playlist[++f]);
                    player = new Player(fis);
                    jLabel4.setText(name[f]);
                    jButton1.setText("Pause");
                    
                    
                    songtotalLength=fis.available();
                    
                    
                    
                        pauseLocation=songtotalLength;
                    
                    try {
			fis.skip(songtotalLength-pauseLocation);
		} catch (IOException e1) {
			
			
		}
                    
          
                new Thread()
                {
                    public void run()
                    {
                        try {
                            Playing=true;
                            count++;
                            player.play();
                           
                            
                                    } catch (JavaLayerException ex) {
                            
                        }
                        if(player.isComplete())
                        try {
                            checkComplete();
                                    
                                    } catch (InterruptedException | JavaLayerException | IOException ex) {
                            Logger.getLogger(PlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }}
                }.start();
                
              
                }
		
	}
    
    
    void checkComplete() throws InterruptedException, JavaLayerException, IOException
    {
        stop();
        playnext();
        print();
    }
    
    
    

	
	void stop() throws InterruptedException, JavaLayerException
	{
		if(Playing)
                player.close();	
                Playing=false;
                jLabel4.setText("Nothing Playing right now... Hit the Play Button");
                count=0;
                jButton1.setText("Play");
	}
        
        
        
	
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
